### ISSUE TITLE
How to pass paramaters using template string literal?

### ISSUE THREAD

**Issue by HMFive** [junigar/firebird-query#5]
When using parameters

static async getCols() {
    const columnB = 'COLUMN_B';
    return await db.queryRaw`
      SELECT COLUMN_A FROM TABLE_A ORDER BY ${columnB}`
      .execute();
  }

This return SELECT COLUMN_A FROM TABLE_A ORDER BY 'COLUMN_B' instead of SELECT COLUMN_A FROM TABLE_A ORDER BY COLUMN_B. This is works on most of WHERE conditions I tried but when it comes to ORDER BY it doesnt work

**Comment by junigar** [comment]
The library was not designed to handle dynamic quering, columns or any other low level DB statement at all. That's why `queryRaw` implements by default a escape function, that puts quotes between any string, which is causing the error.

However, it may be interesting to expand `sqlBuilder` functionality, currently suporting `type QueryParam = PrimetiveValue | WhereObject` as argument.
If you add an option to support a function, it may be possible to make your query work.


Example of the desired behavior:
```typescript
const column_a = 'COLUMN_A';
const table_a = 'TABLE_A';
const other_param = 1;


await db.queryRaw`
    SELECT ${(escapeFunction) => column_a} 
    FROM ${(escape) => table_a} 
    WHERE ${(esc)=> `${column_a} < ${esc(other_param)}` }.execute()`
    // --> SELECT COLUMN_A FROM TABLE_A WHERE COLUMN_A <  '1'
```

**Comment by HMFive** [comment]
I added another condition to sqlBuilder to check if the passed parameter is a function. 
```js
const sqlBuilder = (strings, params) => {
    return strings
        .map((cur, i) => {
        const param = params[i];
        if (isWhereObject(param)) {
            const conditions = param;
            const conditionResult = buildWhereClause(conditions);
            return cur + conditionResult;
        }
        else if (isPrimitiveValue(param)) {
            const isLastStr = i === strings.length - 1;
            const valueResult = !isLastStr ? escape(param) : "";
            return cur + valueResult;
        } 
        else if (typeof param === 'function') {
            return cur + param()
        }
        else {
            return "";
        }
    })
        .join("");
};
```
Then sent the following parameter
```js
const colA = 'COLUMN_A';

return await db.getDb().queryRaw`
   SELECT ${() => colA.replace(/'/g, '')} FROM TABLE_A WHERE ${{
   COLUMN_B: 'Pcs',
}}`.execute();
```
This returns `SELECT COLUMN_A FROM TABLE_A WHERE COLUMN_B = 'Pcs'`. This seems to the job but I am not sure it is effective against sql injection

**Comment by junigar** [comment]
The code its almost doing what I first suggest. 

FIX:
Inside the else statement, send the Firebird.escape function to the `param()` callback like following
`else if (typeof param === 'function') {
            return cur + param(Firebird.escape)
        }`

This way, the `escape` function to prevent SQL injection will be available without needing to import it form `Firebird` wich is a deep dependency.
`FROM ${(escFn) => escFn(table_a)}` should do the trick.

**Comment by junigar** [comment]
It is my pleasure to announce a new minor version of the library. Featuring `ManuallyEscapedStatement`, to solve this precise issue.
Please, read de docs for more info.
